API Key:
  openai: "sk-eUXrnuOoH3cZQwVyD21b886e583745F09e2b95AaD7C611D3"
  deepseek: "sk-7f3baf18d09f4d928ffb28a89358cabd"
  tmdb: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkYTJlNjg1MTE2Y2ZhYjdiODMyNGExOTY4NmU3NWM3MiIsIm5iZiI6MTc2NTI2MjcwMS4yNDg5OTk4LCJzdWIiOiI2OTM3YzU2ZDAyNmIyNjk2YzNlYjFhOTMiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.wLY9hDOISSo-ZOeBCKQ9PqhYMp3li7K_KUb7QXu7sPA"
  spotipy_access_token: "BQAwFy2R9umwPDXp9sEDhO627ROwIbjVDeia1cC7OG6elxnvtlyoIUPZCx2jIL6X5zFi2G8pgytnW1VoMTZOK1vB0sqOMOzQwp0rOJXdtwhvPUlzJG4yuTeW4eHSL1VE65_ahzlYcM5llt6hx0u8mz1sjpSyu6xuNE17T6u0_Bx-03rJHnC2rOX6fAjsXVUBDI0DfwL6ttfD0IZWkks_sEloUdzOMA8_McIkboRVX33yLHMc3CZvrNAmFRrNt9rBCqVd15ZQ7Zml8eNplBODcOuRrhW2CPXvUt3KyROEfL4h19UvwRIJsPebADJm0qUbxpbxnn_c-npLQw8X53ovKNKAEOM8QKvCRkFI8QWlHxGjpC3lH75ja7vtXJA9LeEWcLGNLremvGNBnWs"
  lastfm: "d214ed9df84f601f4bf300a9396f38d1"
  openai_base_url: "https://api.rcouyi.com/v1"
